package com.uts.sep.entity;
// Generated Sep 25, 2017 7:42:08 PM by Hibernate Tools 4.3.1



/**
 * AdminTbl generated by hbm2java
 */
public class AdminTbl  implements java.io.Serializable {


     private Integer userId;
     private UserTbl userTbl;
     private int authorityLevel;

    public AdminTbl() {
    }

    public AdminTbl(UserTbl userTbl, int authorityLevel) {
       this.userTbl = userTbl;
       this.authorityLevel = authorityLevel;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public UserTbl getUserTbl() {
        return this.userTbl;
    }
    
    public void setUserTbl(UserTbl userTbl) {
        this.userTbl = userTbl;
    }
    public int getAuthorityLevel() {
        return this.authorityLevel;
    }
    
    public void setAuthorityLevel(int authorityLevel) {
        this.authorityLevel = authorityLevel;
    }




}


