package com.uts.sep.entity;
// Generated Oct 14, 2017 5:40:16 PM by Hibernate Tools 4.3.1



/**
 * AdminTbl generated by hbm2java
 */
public class AdminTbl  implements java.io.Serializable {


     private Integer adminId;
     private String adminName;

    public AdminTbl() {
    }

    public AdminTbl(String adminName) {
       this.adminName = adminName;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
}


