package com.uts.sep.entity;
// Generated 23-Aug-2017 14:07:11 by Hibernate Tools 4.3.1
import java.io.Serializable;
/**
 * AdminTbl generated by hbm2java
 */
public class AdminTbl implements Serializable {

    private Integer adminId;
    private String adminName;

    public AdminTbl() {
    }

    public AdminTbl(String adminName) {
        this.adminName = adminName;
    }

    public Integer getAdminId() {
        return this.adminId;
    }

    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    public String getAdminName() {
        return this.adminName;
    }

    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

}
