package com.uts.sep.entity;
// Generated Oct 14, 2017 5:40:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CustomerTbl generated by hbm2java
 */
public class CustomerTbl  implements java.io.Serializable {


     private int customerId;
     private OrderTbl orderTbl;
     private String customerName;
     private String customerAddress;
     private String email;
     private int creditCardno;
     private Date dob;

    public CustomerTbl() {
    }

	
    public CustomerTbl(int customerId, String customerName, String customerAddress, String email, int creditCardno, Date dob) {
        this.customerId = customerId;
        this.customerName = customerName;
        this.customerAddress = customerAddress;
        this.email = email;
        this.creditCardno = creditCardno;
        this.dob = dob;
    }
    public CustomerTbl(int customerId, OrderTbl orderTbl, String customerName, String customerAddress, String email, int creditCardno, Date dob) {
       this.customerId = customerId;
       this.orderTbl = orderTbl;
       this.customerName = customerName;
       this.customerAddress = customerAddress;
       this.email = email;
       this.creditCardno = creditCardno;
       this.dob = dob;
    }
   
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    public OrderTbl getOrderTbl() {
        return this.orderTbl;
    }
    
    public void setOrderTbl(OrderTbl orderTbl) {
        this.orderTbl = orderTbl;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getCreditCardno() {
        return this.creditCardno;
    }
    
    public void setCreditCardno(int creditCardno) {
        this.creditCardno = creditCardno;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }




}


