package com.uts.sep.entity;
// Generated Oct 3, 2017 10:49:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CustomerTbl generated by hbm2java
 */
public class CustomerTbl  implements java.io.Serializable {


     private int userId;
     private OrderTbl orderTbl;
     private String customerAddress;
     private String email;
     private int creditCardno;
     private Date dob;

    public CustomerTbl() {
    }

	
    public CustomerTbl(int userId, String customerAddress, String email, int creditCardno, Date dob) {
        this.userId = userId;
        this.customerAddress = customerAddress;
        this.email = email;
        this.creditCardno = creditCardno;
        this.dob = dob;
    }
    public CustomerTbl(int userId, OrderTbl orderTbl, String customerAddress, String email, int creditCardno, Date dob) {
       this.userId = userId;
       this.orderTbl = orderTbl;
       this.customerAddress = customerAddress;
       this.email = email;
       this.creditCardno = creditCardno;
       this.dob = dob;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public OrderTbl getOrderTbl() {
        return this.orderTbl;
    }
    
    public void setOrderTbl(OrderTbl orderTbl) {
        this.orderTbl = orderTbl;
    }
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getCreditCardno() {
        return this.creditCardno;
    }
    
    public void setCreditCardno(int creditCardno) {
        this.creditCardno = creditCardno;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }




}


