package com.uts.sep.entity;
// Generated Oct 14, 2017 5:40:16 PM by Hibernate Tools 4.3.1



/**
 * OrderDetailTbl generated by hbm2java
 */
public class OrderDetailTbl  implements java.io.Serializable {


     private int orderId;
     private OrderTbl orderTbl;
     private int itemId;
     private int quantity;
     private String orderDetailName;
     private double unitCost;
     private double subtotal;

    public OrderDetailTbl() {
    }

    public OrderDetailTbl(OrderTbl orderTbl, int itemId, int quantity, String orderDetailName, double unitCost, double subtotal) {
       this.orderTbl = orderTbl;
       this.itemId = itemId;
       this.quantity = quantity;
       this.orderDetailName = orderDetailName;
       this.unitCost = unitCost;
       this.subtotal = subtotal;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public OrderTbl getOrderTbl() {
        return this.orderTbl;
    }
    
    public void setOrderTbl(OrderTbl orderTbl) {
        this.orderTbl = orderTbl;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public String getOrderDetailName() {
        return this.orderDetailName;
    }
    
    public void setOrderDetailName(String orderDetailName) {
        this.orderDetailName = orderDetailName;
    }
    public double getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(double unitCost) {
        this.unitCost = unitCost;
    }
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }




}


