package com.uts.sep.entity;
// Generated 23-Aug-2017 14:07:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.io.Serializable;
/**
 * OrderTbl generated by hbm2java
 */
public class OrderTbl  implements Serializable {


     private Integer orderId;
     private CustomerTbl customerTblByCustomerName;
     private CustomerTbl customerTblByCustomerId;
     private ShippingTbl shippingTbl;
     private int orderStatus;
     private Date dateCreated;
     private double payment;
     private Set orderDetailTbls = new HashSet(0);
     private Set customerTbls = new HashSet(0);

    public OrderTbl() {
    }

	
    public OrderTbl(CustomerTbl customerTblByCustomerName, CustomerTbl customerTblByCustomerId, ShippingTbl shippingTbl, int orderStatus, Date dateCreated, double payment) {
        this.customerTblByCustomerName = customerTblByCustomerName;
        this.customerTblByCustomerId = customerTblByCustomerId;
        this.shippingTbl = shippingTbl;
        this.orderStatus = orderStatus;
        this.dateCreated = dateCreated;
        this.payment = payment;
    }
    public OrderTbl(CustomerTbl customerTblByCustomerName, CustomerTbl customerTblByCustomerId, ShippingTbl shippingTbl, int orderStatus, Date dateCreated, double payment, Set orderDetailTbls, Set customerTbls) {
       this.customerTblByCustomerName = customerTblByCustomerName;
       this.customerTblByCustomerId = customerTblByCustomerId;
       this.shippingTbl = shippingTbl;
       this.orderStatus = orderStatus;
       this.dateCreated = dateCreated;
       this.payment = payment;
       this.orderDetailTbls = orderDetailTbls;
       this.customerTbls = customerTbls;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public CustomerTbl getCustomerTblByCustomerName() {
        return this.customerTblByCustomerName;
    }
    
    public void setCustomerTblByCustomerName(CustomerTbl customerTblByCustomerName) {
        this.customerTblByCustomerName = customerTblByCustomerName;
    }
    public CustomerTbl getCustomerTblByCustomerId() {
        return this.customerTblByCustomerId;
    }
    
    public void setCustomerTblByCustomerId(CustomerTbl customerTblByCustomerId) {
        this.customerTblByCustomerId = customerTblByCustomerId;
    }
    public ShippingTbl getShippingTbl() {
        return this.shippingTbl;
    }
    
    public void setShippingTbl(ShippingTbl shippingTbl) {
        this.shippingTbl = shippingTbl;
    }
    public int getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(int orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public double getPayment() {
        return this.payment;
    }
    
    public void setPayment(double payment) {
        this.payment = payment;
    }
    public Set getOrderDetailTbls() {
        return this.orderDetailTbls;
    }
    
    public void setOrderDetailTbls(Set orderDetailTbls) {
        this.orderDetailTbls = orderDetailTbls;
    }
    public Set getCustomerTbls() {
        return this.customerTbls;
    }
    
    public void setCustomerTbls(Set customerTbls) {
        this.customerTbls = customerTbls;
    }




}


