package com.uts.sep.entity;
// Generated Sep 25, 2017 7:42:08 PM by Hibernate Tools 4.3.1



/**
 * SellerTbl generated by hbm2java
 */
public class SellerTbl  implements java.io.Serializable {


     private int userId;
     private UserTbl userTbl;
     private int sellerCredit;

    public SellerTbl() {
    }

    public SellerTbl(UserTbl userTbl, int sellerCredit) {
       this.userTbl = userTbl;
       this.sellerCredit = sellerCredit;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public UserTbl getUserTbl() {
        return this.userTbl;
    }
    
    public void setUserTbl(UserTbl userTbl) {
        this.userTbl = userTbl;
    }
    public int getSellerCredit() {
        return this.sellerCredit;
    }
    
    public void setSellerCredit(int sellerCredit) {
        this.sellerCredit = sellerCredit;
    }




}


