package com.uts.sep.entity;
// Generated Oct 3, 2017 10:49:09 PM by Hibernate Tools 4.3.1



/**
 * SellerTbl generated by hbm2java
 */
public class SellerTbl  implements java.io.Serializable {


     private int userId;
     private int sellerCredit;

    public SellerTbl() {
    }

    public SellerTbl(int userId, int sellerCredit) {
       this.userId = userId;
       this.sellerCredit = sellerCredit;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getSellerCredit() {
        return this.sellerCredit;
    }
    
    public void setSellerCredit(int sellerCredit) {
        this.sellerCredit = sellerCredit;
    }




}


