package com.uts.sep.entity;
// Generated Oct 3, 2017 10:49:09 PM by Hibernate Tools 4.3.1



/**
 * ShoppingCartItemTblId generated by hbm2java
 */
public class ShoppingCartItemTblId  implements java.io.Serializable {


     private int itemId;
     private int shoppingCartId;

    public ShoppingCartItemTblId() {
    }

    public ShoppingCartItemTblId(int itemId, int shoppingCartId) {
       this.itemId = itemId;
       this.shoppingCartId = shoppingCartId;
    }
   
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public int getShoppingCartId() {
        return this.shoppingCartId;
    }
    
    public void setShoppingCartId(int shoppingCartId) {
        this.shoppingCartId = shoppingCartId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ShoppingCartItemTblId) ) return false;
		 ShoppingCartItemTblId castOther = ( ShoppingCartItemTblId ) other; 
         
		 return (this.getItemId()==castOther.getItemId())
 && (this.getShoppingCartId()==castOther.getShoppingCartId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getItemId();
         result = 37 * result + this.getShoppingCartId();
         return result;
   }   


}


