package com.uts.sep.entity;
// Generated Oct 3, 2017 10:49:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ShoppingCartTbl generated by hbm2java
 */
public class ShoppingCartTbl  implements java.io.Serializable {


     private int shoppingCartId;
     private UserTbl userTbl;
     private Set shoppingCartItemTbls = new HashSet(0);

    public ShoppingCartTbl() {
    }

	
    public ShoppingCartTbl(int shoppingCartId, UserTbl userTbl) {
        this.shoppingCartId = shoppingCartId;
        this.userTbl = userTbl;
    }
    public ShoppingCartTbl(int shoppingCartId, UserTbl userTbl, Set shoppingCartItemTbls) {
       this.shoppingCartId = shoppingCartId;
       this.userTbl = userTbl;
       this.shoppingCartItemTbls = shoppingCartItemTbls;
    }
   
    public int getShoppingCartId() {
        return this.shoppingCartId;
    }
    
    public void setShoppingCartId(int shoppingCartId) {
        this.shoppingCartId = shoppingCartId;
    }
    public UserTbl getUserTbl() {
        return this.userTbl;
    }
    
    public void setUserTbl(UserTbl userTbl) {
        this.userTbl = userTbl;
    }
    public Set getShoppingCartItemTbls() {
        return this.shoppingCartItemTbls;
    }
    
    public void setShoppingCartItemTbls(Set shoppingCartItemTbls) {
        this.shoppingCartItemTbls = shoppingCartItemTbls;
    }
}


